### ISSUE TITLE
Enable Date of Last IP Review to be written as a date

### ISSUE THREAD

**Issue by idg10** [endjin/Endjin.Ip.Maturity.Matrix#1]
Currently, the only way a project can express the `Date of Last IP Review` is to put the resulting score in the `imm.yaml`, e.g.:

```yaml
-
    Name: 'Date of Last IP Review'
    Id: da4ed776-0365-4d8a-a297-c4e91a14d646
    Measures:
        -
            Score: 1
            Description: None
```

There is an obvious design flaw with this approach: the score is a function of elapsed time:

Score|Condition
---|---
1|> 3 months
2|> 1 month
3|< 1 month

If I review a project today its score is 3. But one month from today that should drop to 2, and another 2 months after that it should drop to 1. But this would require someone to go and update it. Since the whole point of this entry is to show how long it has been since anyone looked at the project, unhelpful that neglect will automatically produce an incorrect high score.

It should be possible to write something like this:

```yaml
-
    Name: 'Date of Last IP Review'
    Id: da4ed776-0365-4d8a-a297-c4e91a14d646
    Measures:
        -
            Date: 2019-11-28
```

The IMM badge endpoint should then automatically calculate the score based on the current date. This way, if a project is neglected, its score drops automatically. 

For this to work the rule definition would need to be able to define the rules by which the calculation is performed.

Currently it looks like this:

```yaml
-
    Name: 'Date of Last IP Review'
    Id: da4ed776-0365-4d8a-a297-c4e91a14d646
    DataType: Discrete
    Measures:
        -
            Score: 0
            Description: None
        -
            Score: 1
            Description: '> 3 months'
        -
            Score: 2
            Description: '> 1 month'
        -
            Score: 3
            Description: '< 1 month'
```

The text here is purely descriptive, but we're not that far off. We'd need to introduce a new `DataType`, perhaps `Age`. We could as an ad hoc hack choose to interpret the `Description` formally for certain data types. But I'd prefer we did something less 'magic'. So I'd like to see something like this:

```yaml
-
    Name: 'Date of Last IP Review'
    Id: da4ed776-0365-4d8a-a297-c4e91a14d646
    DataType: Age
    Measures:
        -
            Score: 3
            Age: <P1M
            Description: '< 1 month'
        -
            Score: 2
            Age: <P3M
            Description: '> 1 month'
        -
            Score: 1
            Age: *
            Description: '> 3 months'
        -
            Score: 0
            Description: None
```

The idea here would be that the `Age` can begin with either `<` or `*`. If it starts with `<`, then if the age is under the specified value (specified as an ISO8601 duration) then that's a match, So being under 1 month would score you 3. If it's not a match we'd move onto the next rule. An `Age` of `*` matches any age as long as the age is known. The final rule does not specify an `Age` at all, and will only come into play if the none of the other rules match (which would happen only if the project didn't specify an age at all).
