### ISSUE TITLE
Enable "not applicable" where acceptable

### ISSUE THREAD

**Issue by idg10** [endjin/Endjin.Ip.Maturity.Matrix#13]
Some measures are not appropriate for all projects. For example, `Corvus.Monitoring` does not have any deployment scripts because it's something that is only ever deployed as a component of something else. It does not require any artifacts up in Azure or in a container, so there's nothing to do here.

But currently we are nontheless required to provide a score for the `Deployment` rule. If we do not provide a value for this, we lose points in the overall IMM score, which is misleading because there's nothing we could do that would improve this library in this respect. Equally it would be misleading just to score ourselves full marks on this area when we do nothing at all related to deployment in this project.

So we think it should be possible for projects to opt out of this measure. There are other measures for which this may also be appropriate (e.g., Insights and Telemetry are probably not something you want in a string manipulation library).

Not all measures should be optional, but it should be possible to define some as optional.

Additionally, for cumulative measures, individual elements might be optional. For example, the `Design & Implementation Documentation` measure includes points for "Logical, infrastructure, security & ops views" which might not be applicable to all library code. So we would want it to be possible to score full marks without checking all boxes in those cases, but without needing to mark the entire measure as not applicable.

**Comment by idg10** [comment]
I'm proposing we allow a `CanOptOut: true` entry both at the rule definition level and the measure definition level.

For cases where the entire rule might not apply for all IP, the rule definition will look like this:

```yaml
-
    Name: Deployment
    Id: edea4593-d2dd-485b-bc1b-aaaf18f098f9
    DataType: Continuous
    CanOptOut: true
    Measures:
        -
            Score: 0
            Description: None
        -
            Score: 1
            Description: 'Scripted & Documented'
        -
            Score: 1
            Description: Templated
        -
            Score: 1
            Description: 'Multi-tenanted - as a Service'
```

A component for which a rule is not applicable (e.g., a component that might be deployed as part of something else, but which has no deployment requirements of its own) would then have this in its `imm.yaml`:

```yaml
-
    Name: Deployment
    Id: edea4593-d2dd-485b-bc1b-aaaf18f098f9
    OptOut: true
```

For continuous rules in which individual measures might not be applicable these settings go in the individual measures, so the definition might look like this:

```yaml
-
    Name: 'Design & Implementation Documentation'
    Id: f026d5a2-ce1a-4e04-af15-5a35792b164b
    DataType: Continuous
    Measures:
        -
            Score: 0
            Description: None
        -
            Score: 1
            Description: 'Up-to-date architecture & high level conceptual docs & diagrams'
        -
            Score: 1
            Description: 'Logical infrastructure security & ops views'
            CanOptOut: true
        -
            Score: 1
            Description: 'Constraints & extensibility (obtained from benchmarks & specs)'
            CanOptOut: true
```
