### ISSUE TITLE
Enable Framework Version to be written as the version

### ISSUE THREAD

**Issue by idg10** [endjin/Endjin.Ip.Maturity.Matrix#3]
Currently, the only way a project can express the `Framework Version` is to put the resulting score in the imm.yaml, e.g.:

```yaml
-
    Name: 'Framework Version'
    Id: 6c0402b3-f0e3-4bd7-83fe-04bb6dca7924
    Measures:
        -
            Score: 2
            Description: 'Using the most current LTS version'
```

This suffers from exactly the same problem described for date-based rules in #1 - the purpose of these rules is to provide a signal indicating that the code is out of date, but they need positive action to provide correct information.

If code is neglected, measure of this form will automatically become wrong over time. And since the only purpose of these measures is to let you know that code has fallen out of date, it means that these rules do not serve their intended purpose in their current form.

It would be far better if the `imm.yaml` simply stated what was in use, and then the IMM infrastructure can calculate the score from that based on a knowledge of what's current. so the IMM in a project might look like this:

```yaml
-
    Name: 'Framework Version'
    Id: 6c0402b3-f0e3-4bd7-83fe-04bb6dca7924
    Measures:
        -
            Framework: 'netcoreapp2.1'
```

Evaluated on 29th November 2019, this would score 3 points because .NET Core 2.1 is the most current LTS version. Once Microsoft ships .NET Core 3.1, this score would drop automatically to 2 (using a supported LTS version but not the most current one). And when at some point in the future .NET Core 2.1 falls out of LTS (which at the earliest will be 21st August 2021) this will drop to 1 points.

The crucial point here is that these changes in score all happen without anyone needing to edit the project's `imm.yaml`. It just decays automatically over time. (This doesn't happen with the current approach where you put the `Score` directly in the `imm.yaml`.)

We don't really want to bake knowledge of which frameworks are current into the IMM infrastructure code itself. This is something that it should be possible to do through the rule definitions. That way, we can introduce similar rules for frameworks other than .NET (e.g., Java) without needing code changes. Today, these rules look like this:

```yaml
-
    Name: 'Framework Version'
    Id: 6c0402b3-f0e3-4bd7-83fe-04bb6dca7924
    DataType: Discrete
    Measures:
        -
            Score: 0
            Description: None
        -
            Score: 1
            Description: 'Using an unsupported version'
        -
            Score: 2
            Description: 'Using a LTS version'
        -
            Score: 3
            Description: 'Using the most current LTS version'
```

I'm proposing something more like this:

```yaml
-
    Name: 'Framework Version'
    Id: 6c0402b3-f0e3-4bd7-83fe-04bb6dca7924
    DataType: DependencyVersion
    Measures:
        -
            Score: 3
            Framework: 'netcoreapp6.0'
            Description: 'Using the most current LTS version'
        -
            Score: 2
            Framework: 'netcoreapp3.1'
            Description: 'Using a LTS version'
        -
            Score: 2
            Framework: 'netcoreapp2.1'
            Description: 'Using a LTS version'
        -
            Score: 1
            Framework: '*'
            Description: 'Using an unsupported version'
        -
            Score: 0
            Description: None
```

This is based on a possible future. It relies on Microsoft successfully sticking to their [stated plan](https://github.com/dotnet/core/blob/master/roadmap.md) of shipping .NET 6.0 as the next LTS version after .NET Core 3.1, but also extending .NET Core 2.1 support beyond its current projected end date with the effect that versions 2.1, 3.1, and 6.0 (all LTS versions) are all in current support simultaneously. (It's not the current plan, but Microsoft has a tendency to extend support beyond their initial conservative promises, so it's a fairly plausible scenario for where we'll be in November 2021. The main reason for imagining this particular scenario is that it shows what it looks like to have two non-current-but-still-supported LTS versions.)

Today's situation (November 29th 2019) is a little simpler:

```yaml
-
    Name: 'Framework Version'
    Id: 6c0402b3-f0e3-4bd7-83fe-04bb6dca7924
    DataType: DependencyVersion
    Measures:
        -
            Score: 3
            Framework: 'netcoreapp2.1'
            Description: 'Using the most current LTS version'
        -
            Score: 1
            Framework: '*'
            Description: 'Using an unsupported version'
        -
            Score: 0
            Description: None
```

Right now you can't actually get 2 points, because there's only one current LTS version of .NET Core: .NET Core 2.1. Once .NET Core 3.1 ships, it'll look like this:

```yaml
-
    Name: 'Framework Version'
    Id: 6c0402b3-f0e3-4bd7-83fe-04bb6dca7924
    DataType: DependencyVersion
    Measures:
        -
            Score: 3
            Framework: 'netcoreapp3.1'
            Description: 'Using the most current LTS version'
        -
            Score: 2
            Framework: 'netcoreapp2.1'
            Description: 'Using a LTS version'
        -
            Score: 1
            Framework: '*'
            Description: 'Using an unsupported version'
        -
            Score: 0
            Description: None
```

Note that in all these examples, you get a point for having bothered to say what your version was, because that's slightly better than not even stating that. This copies how the current version of this rule is formulated.

**Comment by idg10** [comment]
This rule might need some more thought around libraries, because currently it only really works for applications: with an application, you definitely want to be on an LTS version, and you ideally want to be the most current LTS version. But if a library targets the latest LTS runtime, that can be a liabilty.

On the day that I write this comment, .NET Core 3.1 is the current LTS version of .NET Core, and has been for about 2 days now. (As https://devblogs.microsoft.com/dotnet/announcing-net-core-3-1/ shows, it was released on 2019/12/03.) Does that mean that we should award maximum points to a library that targests `netcoreapp3.1`? Should that score better than one that targets `netstandard2.0`?

There are two problems here:

- Libraries should normally target versions of .NET Standard, not .NET Core
- Libraries that force you onto the latest version are not necessarily desirable

The obvious response to the first point is: maybe we should just include .NET Standard versions too, e.g.:

```yaml
-
    Name: 'Framework Version'
    Id: 6c0402b3-f0e3-4bd7-83fe-04bb6dca7924
    DataType: DependencyVersion
    Measures:
        -
            Score: 3
            Framework: 'netcoreapp3.1'
            Description: 'Using the most current LTS version'
        -
            Score: 3
            Framework: 'netstandard2.1'
            Description: 'Using the version of .NET Standard associated with the most current LTS version'
        -
            Score: 2
            Framework: 'netcoreapp2.1'
            Description: 'Using a LTS version'
        -
            Score: 2
            Framework: 'netstandard2.0'
            Description: 'Using a version of .NET Standard associated with a LTS version'
        -
            Score: 1
            Framework: '*'
            Description: 'Using an unsupported version'
        -
            Score: 0
            Description: None
```
Superfically that makes sense, but it turns out to be counterproductive. What does a library need to do to score 100% on its IMM? Consider these fictional libraries:

Library | TargetFramework | IMM score
--- | --- | ---
`Corvus.EasyGoing` | `netstandard1.4` | 1
`Corvus.Pragmatic` | `netstandard2.0` | 2
`Corvus.Primadonna` | `netstandard2.1` | 3

This illustrates that the rules above provide peverse incentives: the highest-scoring component here would actually be unusable today in an Azure Function. (At the time of writing this, Azure Functions do not yet support .NET Core 3.0 or 3.1. They do not support any version of .NET capable of using a .NET Standard 2.1


The problem here is that there are really two separate questions that seem related, but which can be in conflict:

* How up to date is this library?
* Will this library work on the current versions of everything?

In a sense they are related: a library that hasn't been looked at for years is in risk of not working in a current environment, and so in general we'd want a library with recent active development to score better than one that is moribund. Where this goes wrong is at the bleeding edge: a brand new library built to target only the very latest LTS runtime might actually be effectively unusuable. (It will be right now, on 2019/12/05, because neither Azure App Service nor Azure Functions support .NET Core 3.1 yet.)

Looking at the table, you might think that inverting the score would fix the problem. It certainly addresses the second bullet point above, because newer frameworks always support older versions of .NET Standard. But it then fails to provide any sense of an answer to the first question.

An alternative would be to subtly change how we interpret this particular rule on library code. Whereas an application specifies which framework version it targets, a libary could specify *the latest version it was tested against*.

That way, we would preserve this score's ability to answer the "How up to date is this library?" question, while removing the peverse incentive to pick a target framework that actively makes the library less useful.

It doesn't strictly answer the second question: technically, knowing that a component gets a perfect score on this measure won't tell you whether it'll work on current bits because it doesn't take into account the possibility that the thing is so bleeding edge that you can't use it. However, my current view is that this probably doesn't matter very much. It will quickly become apparent when you try to use the component that it doesn't support your target framework. The IMM, then, shouldn't waste much time on replicating that capability. It's more useful for it to give a sense of whether the component is lovingly kept up to date or whether it is rotting away, so all we really need to do is make sure that this rule doesn't actively encourage helpful choices. Reframing this rule (in the library case) as "What's the latest framework version this is known to work on?" seems like it would do that.
